swagger: '2.0'

info:
  title: User API
  version: "0.3.0"

paths:
  /organizations/{organization}:
    get:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.get_organization_info
      summary: Returns organization info.
      parameters:
        - name: organization
          in: path
          required: true
          type: string
          format: path
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              user_info:
                type: string
                description: Organization information
  /repositories/{repository}:
    get:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.get_repository_info
      summary: Returns repository information.
      parameters:
        - name: repository
          in: path
          required: true
          type: string
          format: path
        - name: time_range
          in: query
          type: string
      responses:
        200:
          description: Successful response.
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
  /users/{username}:
    get:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.get_user_info
      summary: Returns user information.
      parameters:
        - name: username
          in: path
          required: true
          type: string
          format: path
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              user_info:
                type: string
                description: User information
  /organizations/{organization}/repositories/{repository}/users/{user}/commits:
    get:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.get_commits_info
      summary: Returns commits info.
      parameters:
        - name: organization
          in: path
          required: true
          type: string
          format: path
        - name: repository
          in: path
          required: true
          type: string
          format: path
        - name: user
          in: path
          required: true
          type: string
          format: path
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              user_info:
                type: string
                description: Commits of user information


definitions:
  Item:
    type: object
    properties:
      commits_count:
        type: integer
      yyyymmdd_date:
        type: string
