swagger: '2.0'

# OPENAPI definition for the gm_analytics API
info:
        title: gm_analytucs API
        version: 0.1.0

patchs:
     /repos/{repo}/collabs/{collaborator}/commits:
         get:
             operationId: gm_analytics.handlers.get_commits
             summary: Return collaborator commits
             parameters:
                 - name: repo
                   in: path
                   required: true
                   type: string
                   format: path
                 - name: collaborator
                   in: path
                   required: true
                   type: string
                   format: path
                   #  responses:
                   #  200:   
~
